package com.codegen.cli;

import com.codegen.core.engine.TemplateEngine;
import com.codegen.core.model.TableInfo;
import picocli.CommandLine;

import java.io.File;
import java.util.Collections;

@CommandLine.Command(name = "codegen", mixinStandardHelpOptions = true, version = "1.0",
        description = "Generates code based on a table name and class name.")
public class Main implements Runnable {

    @CommandLine.Option(names = {"-t", "--table"}, required = true, description = "The table name")
    private String tableName;

    @CommandLine.Option(names = {"-c", "--class"}, required = true, description = "The class name")
    private String className;

    @CommandLine.Option(names = {"-o", "--output"}, required = true, description = "The output directory")
    private String outputDir;

    @CommandLine.Option(names = {"-T", "--template"}, description = "Optional path to a local template file. If not provided, uses the bundled entity.ftl")
    private String templatePath;

    public static void main(String[] args) {
        int exitCode = new CommandLine(new Main()).execute(args);
        System.exit(exitCode);
    }

    @Override
    public void run() {
        try {
            TableInfo tableInfo = new TableInfo()
                    .setTableName(tableName)
                    .setClassName(className)
                    .setComment("Generated by codegen-cli")
                    .setColumns(Collections.emptyList()); // we can mock empty columns for now or user can extend

            TemplateEngine templateEngine = new TemplateEngine();

            String templateName;
            if (templatePath != null && !templatePath.isEmpty()) {
                File tplFile = new File(templatePath);
                if (!tplFile.exists() || !tplFile.isFile()) {
                    System.err.println("Template file not found: " + templatePath);
                    return;
                }
                templateEngine.setTemplateDirectory(tplFile.getParent());
                templateName = tplFile.getName();
            } else {
                templateEngine.setClassForTemplateLoading(Main.class, "/templates");
                templateName = "entity.ftl";
            }

            File outDir = new File(outputDir);
            if (!outDir.exists()) {
                outDir.mkdirs();
            }

            String outputPath = new File(outDir, className + ".java").getAbsolutePath();
            templateEngine.renderToFile(templateName, tableInfo, outputPath);

            System.out.println("Code generated successfully at: " + outputPath);

        } catch (Exception e) {
            System.err.println("Error generating code: " + e.getMessage());
            e.printStackTrace();
        }
    }
}